Dev v1.7.2 (#213)
* Add an up to two minute wait for collecting critical variables, exit upon failure with a notification.

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -16,7 +16,7 @@
 #██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗          SomeWhereOverTheRainBow        #
 #██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝    Contributors:                        #
 #██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗          JackYaz,gspannu,thelonelycoder #
-#██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║    v1.7.1                               #
+#██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║    v1.7.2                               #
 #╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝                                         #
 #################################################################################################################
 
@@ -28,17 +28,25 @@
 export LC_ALL=C
 export PATH="/sbin:/bin:/usr/sbin:/usr/bin:${PATH}"
 
-AI_VERSION="v1.7.1"
+AI_VERSION="v1.7.2"
 export AI_VERSION
 readonly LATEST_URL="https://api.github.com/repos/AdguardTeam/AdGuardHome/releases"
-until [ -n "$REMOTE_VER" ] && [ -n "$REMOTE_BETA" ] && [ -n "$SCHEMA_VER" ]; do 
+varcnt=0
+until [ -n "$REMOTE_VER" ] && [ -n "$REMOTE_BETA" ] && [ -n "$SCHEMA_VER" ]; do
 	[ -z "$REMOTE_VER" ] && REMOTE_VER="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -sL "${LATEST_URL}" | sed -n '/"prerelease": false,/q;p' | tail -4 | grep "tag_name" | cut -d \" -f 4 &)" || true
 	[ -z "$REMOTE_BETA" ] && REMOTE_BETA="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -sL "${LATEST_URL}" | sed -n '/"prerelease": true,/q;p' | tail -4 | grep "tag_name" | cut -d \" -f 4 &)" || true
 	[ -z "$SCHEMA_VER" ] && SCHEMA_VER="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -sL "https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/CHANGELOG.md" | grep -m1 -oE 'schema.*to[[:space:]][0-9]{1,2}' | awk '{ print $NF }' &)" || true
-	wait
+	varcnt="$((varcnt + 1 ))"
+	if [ "${varcnt}" -le 84 ]; then
+		wait
+	else
+		printf "%s/n" "One or more critical variables could not be set in a timely mannor." "Please check your internet connection, or try again later." "The installer script will now exit."
+		sleep 3s
+		exit 1
+	fi
 done
 wait
-
+unset varcnt
 readonly REMOTE_VER REMOTE_BETA SCHEMA_VER
 readonly ADDON_DIR="/jffs/addons/AdGuardHome.d"
 readonly BASE_DIR="/opt/etc"
@@ -443,10 +451,21 @@ check_version() {
 	local RMNSTALL LINSTALL MD5SUM_L MD5SUM_R
 	if [ -f "${TARG_DIR}/installer" ] && [ -f "${AGH_FILE}" ] && [ -z "$2" ]; then
 		if [ -n "$1" ] || { check_connection; }; then
-			LINSTALL="$(awk '{ print }' "${TARG_DIR}/installer" | grep -m1 "^AI_VERSION=" | grep -oE '[0-9]{1,2}([.][0-9]{1,2})([.][0-9]{1,2})' &)" || true
-			RMNSTALL="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -sL "${RURL}/installer" | grep -m1 "^AI_VERSION=" | grep -oE '[0-9]{1,2}([.][0-9]{1,2})([.][0-9]{1,2})' &)" || true
-			MD5SUM_L="$(md5sum "${TARG_DIR}/installer" | cut -d' ' -f1 &)" || true
-			MD5SUM_R="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -fsL "${RURL}/installer" | md5sum | awk '{print $1}' &)" || true
+			local varcnt=0
+			until [ -n "${LINSTALL}" ] && [ -n "${RMNSTALL}" ] && [ -n "${MD5SUM_L}" ] && [ -n "${MD5SUM_R}" ]; do
+				[ -z "${LINSTALL}" ] && LINSTALL="$(awk '{ print }' "${TARG_DIR}/installer" | grep -m1 "^AI_VERSION=" | grep -oE '[0-9]{1,2}([.][0-9]{1,2})([.][0-9]{1,2})' &)" || true
+				[ -z "${RMNSTALL}" ] && RMNSTALL="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -sL "${RURL}/installer" | grep -m1 "^AI_VERSION=" | grep -oE '[0-9]{1,2}([.][0-9]{1,2})([.][0-9]{1,2})' &)" || true
+				[ -z "${MD5SUM_L}" ] && MD5SUM_L="$(md5sum "${TARG_DIR}/installer" | cut -d' ' -f1 &)" || true
+				[ -z "${MD5SUM_R}" ] && MD5SUM_R="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -fsL "${RURL}/installer" | md5sum | awk '{print $1}' &)" || true
+				varcnt="$((varcnt + 1 ))"
+				if [ "${varcnt}" -le 84 ]; then
+					wait
+				else
+					printf "%s/n" "One or more critical variables could not be set in a timely mannor." "Please check your internet connection, or try again later." "The installer script will now exit."
+					sleep 3s
+					exit 1
+				fi
+			done
 			wait
 			if { [ -n "${LINSTALL}" ] && [ -n "${RMNSTALL}" ]; }; then
 				[ -z "${LINSTALL}" ] && exit 1
@@ -604,8 +623,19 @@ download_file() {
 	shift
 	for URL in "$@"; do
 		FILENAME="$(basename "${URL}")"
-		MD5SUM_OLD="$([ -f "${TARG}/${FILENAME}" ] && md5sum "${TARG}/${FILENAME}" | cut -d' ' -f1 &)" || true
-		MD5SUM_CURR="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -fsL "${URL}" | md5sum | awk '{print $1}' &)" || true
+		local varcnt="0"
+		until [ -n "${MD5SUM_CURR}" ]; do
+			if [ -f "${TARG}/${FILENAME}" ]; then
+				[ -z "${MD5SUM_OLD}" ] && MD5SUM_OLD="$(md5sum "${TARG}/${FILENAME}" | cut -d' ' -f1 &)" || true
+			fi
+			[ -z "${MD5SUM_CURR}" ] && MD5SUM_CURR="$(curl --retry 3 --connect-timeout 3 --retry-delay 1 --max-time $((3 * 5)) --retry-all-errors -fsL "${URL}" | md5sum | awk '{print $1}' &)" || true
+			varcnt="$((varcnt + 1 ))"
+			if [ "${varcnt}" -eq 1 ]; then
+				wait
+			else
+				break
+			fi
+		done
 		wait
 		if [ "$(PTXT -n "${MD5SUM_CURR}" | wc -c)" -eq 32 ] && [ "${MD5SUM_CURR}" = "${MD5SUM_OLD}" ]; then
 			PTXT "${INFO} ${FILENAME} is up to date. Skipping..."
