Update installer (#148)
* Update installer
  # fix order of installer processes.

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -17,7 +17,7 @@
 #   | |   _ __   ___ | |_  __ _ | || |  ___  _ __           SomeWhereOverTheRainBow        #
 #   | |  | '_ \ / __|| __|/ _` || || | / _ \| '__|    Contributors:                        #
 #  _| |_ | | | |\__ \| |_| (_| || || ||  __/| |             JackYaz,gspannu,thelonelycoder #
-# |_____||_| |_||___/ \__|\__,_||_||_| \___||_|       v1.4.5                               #
+# |_____||_| |_||___/ \__|\__,_||_||_| \___||_|       v1.4.6                               #
 #                                                                                          #
 ############################################################################################
 
@@ -32,7 +32,7 @@
 # shellcheck disable=SC3045
 # shellcheck disable=SC3057
 
-AI_VERSION="v1.4.5"
+AI_VERSION="v1.4.6"
 readonly LATEST_URL="https://api.github.com/repos/AdguardTeam/AdGuardHome/releases"
 readonly REMOTE_VER="$(curl -sL "$LATEST_URL" | sed -n '/"prerelease": false,/q;p' | tail -4 | grep "tag_name" | cut -d \" -f 4)"
 readonly REMOTE_BETA="$(curl -sL "$LATEST_URL" | sed -n '/"prerelease": true,/q;p' | tail -4 | grep "tag_name" | cut -d \" -f 4)"
@@ -92,9 +92,27 @@ AdGuardHome_authen () {
     PTXT "$ERROR Password entered incorrectly!"
     AdGuardHome_authen "$1"
   fi
+  opkg install python3 python3-pip python3-bcrypt >/dev/null 2>&1
+  if opkg list-installed | grep -q apache; then opkg flag user apache apache-utils >/dev/null 2>&1; opkg remove apache apache-utils --force-removal-of-dependent-packages >/dev/null 2>&1; fi
+  if ! opkg list-installed | grep -q python3-bcrypt; then
+    case "$(/bin/uname -m)" in
+      "aarch64"|"arm64")
+        opkg install go >/dev/null 2>&1
+        ;;
+      "armv7l"|*)
+        if ! opkg list | grep -qw 'go_nohf'; then opkg install go >/dev/null 2>&1; else opkg install go_nohf >/dev/null 2>&1; fi
+        ;;
+    esac
+    export PATH="$PATH":/opt/bin/go/bin
+    export GOROOT=/opt/bin/go
+    export GOBIN=/opt/bin/
+    go install gophers.dev/cmds/bcrypt-tool@latest >/dev/null 2>&1
+    rm -rf go
+  else
+    pip3 install bcrypt >/dev/null 2>&1
+  fi
   local PW1_ENCRYPTED
-  opkg list-installed | grep -q python3-bcrypt && PW1_ENCRYPTED="$(python -c 'import bcrypt; password = b"'${PW1}'"; print(bcrypt.hashpw(password, bcrypt.gensalt(prefix=b"2a", rounds=10)).decode("ascii"))')"
-  opkg list-installed | grep -q python3-bcrypt || PW1_ENCRYPTED="$(/opt/bin/bcrypt-tool hash "${PW1}" 10)"
+  if opkg list-installed | grep -q python3-bcrypt; then PW1_ENCRYPTED="$(python -c 'import bcrypt; password = b"'${PW1}'"; print(bcrypt.hashpw(password, bcrypt.gensalt(prefix=b"2a", rounds=10)).decode("ascii"))')"; elif [ -f "/opt/bin/bcrypt-tool" ]; then PW1_ENCRYPTED="$(/opt/bin/bcrypt-tool hash "${PW1}" 10)"; else PTXT "$ERROR Password could not be set!" "$ERROR Please contact dev."; end_op_message 1; return; fi
   if [ "$1" -eq 0 ]; then
     yaml_nvars_delete "- name:" $YAML_FILE
     yaml_nvars_delete "  password:" $YAML_FILE
@@ -164,25 +182,6 @@ backup_restore () {
     write_manager_script /jffs/scripts/dnsmasq.postconf dnsmasq
     write_manager_script /jffs/scripts/services-stop services-stop
     write_command_script /jffs/scripts/service-event-end 'if echo "$2" | /bin/grep -q "^AdGuardHome"; then { sh /jffs/addons/AdGuardHome.d/AdGuardHome.sh "${1}" & }; fi # Asuswrt-Merlin-AdGuardHome-Installer'
-    opkg install python3 python3-pip python3-bcrypt >/dev/null 2>&1
-    if opkg list-installed | grep -q apache; then opkg flag user apache apache-utils >/dev/null 2>&1; opkg remove apache apache-utils --force-removal-of-dependent-packages >/dev/null 2>&1; fi
-    if ! opkg list-installed | grep -q python3-bcrypt; then
-      case "$(/bin/uname -m)" in
-      "aarch64"|"arm64")
-        opkg install go >/dev/null 2>&1
-        ;;
-      "armv7l"|*)
-        if ! opkg list | grep -qw 'go_nohf'; then opkg install go >/dev/null 2>&1; else opkg install go_nohf >/dev/null 2>&1; fi
-        ;;
-      esac
-      export PATH="$PATH":/opt/bin/go/bin
-      export GOROOT=/opt/bin/go
-      export GOBIN=/opt/bin/
-      go install gophers.dev/cmds/bcrypt-tool@latest >/dev/null 2>&1
-      rm -rf go
-    else
-      pip3 install bcrypt >/dev/null 2>&1
-    fi
     if [ ! -f "/etc/localtime" ]; then PTXT "$INFO Before setting up AdGuardHome, please choose your right timezone!"; set_timezone; fi
     setup_AdGuardHome
     if [ "$?" -ne 0 ]; then
@@ -645,24 +644,6 @@ inst_AdGuardHome () {
   write_manager_script /jffs/scripts/dnsmasq.postconf dnsmasq
   write_manager_script /jffs/scripts/services-stop services-stop
   write_command_script /jffs/scripts/service-event-end 'if echo "$2" | /bin/grep -q "^AdGuardHome"; then { sh /jffs/addons/AdGuardHome.d/AdGuardHome.sh "${1}" & }; fi # Asuswrt-Merlin-AdGuardHome-Installer'
-  opkg install python3 python3-pip python3-bcrypt >/dev/null 2>&1
-  if ! opkg list-installed | grep -q python3-bcrypt; then
-    case "$(/bin/uname -m)" in
-    "aarch64"|"arm64")
-      opkg install go >/dev/null 2>&1
-      ;;
-    "armv7l"|*)
-      if ! opkg list | grep -qw 'go_nohf'; then opkg install go >/dev/null 2>&1; else opkg install go_nohf >/dev/null 2>&1; fi
-      ;;
-    esac
-    export PATH="$PATH":/opt/bin/go/bin
-    export GOROOT=/opt/bin/go
-    export GOBIN=/opt/bin/
-    go install gophers.dev/cmds/bcrypt-tool@latest >/dev/null 2>&1
-    rm -rf go
-  else
-    pip3 install bcrypt >/dev/null 2>&1
-  fi
   if [ ! -f "${ADDON_DIR}/localtime" ]; then PTXT "$INFO Before setting up AdGuardHome, please choose your right timezone!"; set_timezone; fi
   setup_AdGuardHome
   if [ "$?" -ne 0 ]; then
