Update installer
* final attempt to improve checks

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -655,9 +655,9 @@ inst_AdGuardHome () {
   fi
   PTXT "$INFO Starting AdGuardHome..."
   if [ -n "$(pidof AdGuardHome)" ]; then { if { service stop_AdGuardHome >/dev/null 2>&1; }; then sleep 1; elif { /opt/etc/init.d/S99AdGuardHome stop; }; then sleep 1; elif { /opt/etc/init.d/S99AdGuardHome kill; }; then sleep 1; else { killall -q -9 AdGuardHome 2>/dev/null; }; rm -rf /opt/var/run/AdGuardHome.pid 2>/dev/null; sleep 1; fi; }; fi; sleep 1;
-  if [ -n "$(pidof AdGuardHome)" ]; then { until [ -z "$(pidof AdGuardHome)" ]; do sleep 1; done; }; else { /opt/etc/init.d/S99AdGuardHome check; }; fi; sleep 1;
-  if [ -z "$(pidof AdGuardHome)" ]; then { if { service start_AdGuardHome >/dev/null 2>&1; }; then sleep 1; elif { /opt/etc/init.d/S99AdGuardHome start; }; then sleep 1; else PTXT "$ERROR Couldn't start AdGuardHome!" "$ERROR Please send WebUI System Log to dev."; end_op_message 1; return; fi; }; fi; sleep 1;
-  if [ -z "$(pidof AdGuardHome)" ]; then { until [ -n "$(pidof AdGuardHome)" ]; do sleep 1; done; }; else { /opt/etc/init.d/S99AdGuardHome check; }; fi; sleep 1;
+  { until [ -z "$(pidof S99AdGuardHome)" ]; do sleep 1; done; }; sleep 1; { /opt/etc/init.d/S99AdGuardHome check; };
+  if [ -z "$(pidof S99AdGuardHome)" ]; then { if { service start_AdGuardHome >/dev/null 2>&1; }; then sleep 1; elif { /opt/etc/init.d/S99AdGuardHome start; }; then sleep 1; else PTXT "$ERROR Couldn't start AdGuardHome!" "$ERROR Please send WebUI System Log to dev."; end_op_message 1; return; fi; }; fi; sleep 1;
+  { until [ -n "$(pidof AdGuardHome)" ]; do sleep 1; done; }; sleep 1; { /opt/etc/init.d/S99AdGuardHome check; };
   if [ -z "$(pidof AdGuardHome)" ]; then
     PTXT "$ERROR Couldn't start AdGuardHome!" \
          "$ERROR Please send WebUI System Log to dev."
@@ -666,9 +666,7 @@ inst_AdGuardHome () {
   fi
   PTXT "$INFO Please wait while we perform one last check."
   if [ -n "$(pidof AdGuardHome)" ]; then { if { service restart_AdGuardHome >/dev/null 2>&1; }; then sleep 1; elif { /opt/etc/init.d/S99AdGuardHome restart; }; then sleep 1; else PTXT "$ERROR Couldn't start AdGuardHome!" "$ERROR Please send WebUI System Log to dev."; end_op_message 1; return; fi; }; fi; sleep 1;
-  if [ -n "$(pidof AdGuardHome)" ]; then { until [ -z "$(pidof AdGuardHome)" ]; do sleep 1; done; }; else { /opt/etc/init.d/S99AdGuardHome check; }; fi; sleep 1;
-  if [ -z "$(pidof AdGuardHome)" ]; then { until [ -n "$(pidof AdGuardHome)" ]; do sleep 1; done; }; else { /opt/etc/init.d/S99AdGuardHome check; }; fi; sleep 1;
-  if [ -n "$(pidof AdGuardHome)" ]; then { until { [ "$(ping 1.1.1.1 -c1 -W2 >/dev/null 2>&1; printf "%s" "$?")" = "0" ] && [ "$(nslookup google.com 127.0.0.1 >/dev/null 2>&1; printf "%s" "$?")" = "0" ]; }; do sleep 1; done; }; else { /opt/etc/init.d/S99AdGuardHome check; }; fi; sleep 1;
+  { until { [ "$(ping 1.1.1.1 -c1 -W2 >/dev/null 2>&1; printf "%s" "$?")" = "0" ] && [ "$(nslookup google.com 127.0.0.1 >/dev/null 2>&1; printf "%s" "$?")" = "0" ]; }; do sleep 1; done; }; sleep 1; { /opt/etc/init.d/S99AdGuardHome check; };
   PTXT "$INFO AdGuardHome setup is complete."
   end_op_message 0
 }
