Update S99AdGuardHome

diff --git a/S99AdGuardHome b/S99AdGuardHome
--- a/S99AdGuardHome
+++ b/S99AdGuardHome
@@ -637,8 +637,8 @@ ensure_adguardhome_work_dir_permissions() {
 			return 1
 		fi
 	done
-	if ! find "${WORK_DIR}" -type d -exec chmod 777 {} \;; then
-		logger -st "${PROCS}" "Unable to set directory permissions under ${WORK_DIR}."
+	if ! chmod 770 "${WORK_DIR}" || ! find "${WORK_DIR}" -type d -exec chmod 770 {} \;; then
+		logger -st "${PROCS}" "Unable to set directory permissions for ${WORK_DIR}."
 		return 1
 	fi
 	if [ -f "${WORK_DIR}/AdGuardHome.yaml" ] && ! chmod 644 "${WORK_DIR}/AdGuardHome.yaml"; then
